const en = { appName: 'Quick Sort', language: 'Language', difficulty: 'Difficulty', sound: 'Sound', easy: 'Easy', normal: 'Normal', hard: 'Hard', score: 'Score', combo: 'Combo', time: 'Time', threshold: 'Threshold: {value}', smaller: 'Smaller than {value}', atLeast: '{value} or greater', correct: 'Correct!', incorrect: 'Not quite — try the next one.', accuracy: 'Accuracy: {value}%', reset: 'Reset stats', highScore: 'High score', longestStreak: 'Longest streak', settings: 'Open settings', controls: 'Use Left/Right arrows or A/D to choose.' };
const packs = {
    fa: { appName: 'مرتب‌سازی سریع', language: 'زبان', difficulty: 'سختی', sound: 'صدا', easy: 'آسان', normal: 'معمولی', hard: 'سخت', score: 'امتیاز', combo: 'زنجیره', time: 'زمان', threshold: 'آستانه: {value}', smaller: 'کوچک‌تر از {value}', atLeast: '{value} یا بیشتر', correct: 'درست!', incorrect: 'درست نبود — مورد بعدی را امتحان کنید.', accuracy: 'دقت: {value}٪', reset: 'بازنشانی آمار', highScore: 'بالاترین امتیاز', longestStreak: 'طولانی‌ترین زنجیره', settings: 'باز کردن تنظیمات', controls: 'با پیکان چپ/راست یا A/D انتخاب کنید.' },
    ar: { appName: 'الفرز السريع', language: 'اللغة', difficulty: 'الصعوبة', sound: 'الصوت', easy: 'سهل', normal: 'عادي', hard: 'صعب', score: 'النقاط', combo: 'السلسلة', time: 'الوقت', threshold: 'الحد: {value}', smaller: 'أصغر من {value}', atLeast: '{value} أو أكبر', correct: 'صحيح!', incorrect: 'ليست صحيحة — جرّب التالي.', accuracy: 'الدقة: {value}٪', reset: 'إعادة ضبط الإحصاءات', highScore: 'أعلى نقاط', longestStreak: 'أطول سلسلة', settings: 'فتح الإعدادات', controls: 'استخدم السهمين أو A/D للاختيار.' },
    es: { appName: 'Orden rápido', language: 'Idioma', difficulty: 'Dificultad', sound: 'Sonido', easy: 'Fácil', normal: 'Normal', hard: 'Difícil', score: 'Puntos', combo: 'Racha', time: 'Tiempo', threshold: 'Umbral: {value}', smaller: 'Menor que {value}', atLeast: '{value} o mayor', correct: '¡Correcto!', incorrect: 'No exactamente — prueba el siguiente.', accuracy: 'Precisión: {value}%', reset: 'Restablecer estadísticas', highScore: 'Mejor puntuación', longestStreak: 'Racha más larga', settings: 'Abrir ajustes', controls: 'Usa flechas izquierda/derecha o A/D.' },
    fr: { appName: 'Tri rapide', language: 'Langue', difficulty: 'Difficulté', sound: 'Son', easy: 'Facile', normal: 'Normal', hard: 'Difficile', score: 'Score', combo: 'Série', time: 'Temps', threshold: 'Seuil : {value}', smaller: 'Inférieur à {value}', atLeast: '{value} ou plus', correct: 'Correct !', incorrect: 'Pas tout à fait — essayez le suivant.', accuracy: 'Précision : {value} %', reset: 'Réinitialiser les statistiques', highScore: 'Meilleur score', longestStreak: 'Meilleure série', settings: 'Ouvrir les réglages', controls: 'Utilisez les flèches ou A/D.' },
    de: { appName: 'Schnellsortierung', language: 'Sprache', difficulty: 'Schwierigkeit', sound: 'Ton', easy: 'Leicht', normal: 'Normal', hard: 'Schwer', score: 'Punkte', combo: 'Serie', time: 'Zeit', threshold: 'Schwelle: {value}', smaller: 'Kleiner als {value}', atLeast: '{value} oder größer', correct: 'Richtig!', incorrect: 'Nicht ganz — weiter zum nächsten.', accuracy: 'Genauigkeit: {value} %', reset: 'Statistik zurücksetzen', highScore: 'Höchste Punktzahl', longestStreak: 'Längste Serie', settings: 'Einstellungen öffnen', controls: 'Pfeiltasten oder A/D verwenden.' },
    tr: { appName: 'Hızlı Sınıflandır', language: 'Dil', difficulty: 'Zorluk', sound: 'Ses', easy: 'Kolay', normal: 'Normal', hard: 'Zor', score: 'Puan', combo: 'Seri', time: 'Süre', threshold: 'Eşik: {value}', smaller: '{value} değerinden küçük', atLeast: '{value} veya büyük', correct: 'Doğru!', incorrect: 'Tam değil — sıradakini deneyin.', accuracy: 'Doğruluk: %{value}', reset: 'İstatistikleri sıfırla', highScore: 'En yüksek puan', longestStreak: 'En uzun seri', settings: 'Ayarları aç', controls: 'Sol/sağ okları veya A/D kullanın.' },
    sv: { appName: 'Snabbsortering', language: 'Språk', difficulty: 'Svårighetsgrad', sound: 'Ljud', easy: 'Lätt', normal: 'Normal', hard: 'Svår', score: 'Poäng', combo: 'Kombination', time: 'Tid', threshold: 'Tröskel: {value}', smaller: 'Mindre än {value}', atLeast: '{value} eller större', correct: 'Rätt!', incorrect: 'Inte riktigt — prova nästa.', accuracy: 'Träffsäkerhet: {value}%', reset: 'Återställ statistik', highScore: 'Högsta poäng', longestStreak: 'Längsta svit', settings: 'Öppna inställningar', controls: 'Använd vänster/höger-pilar eller A/D.' },
    et: { appName: 'Kiirsorteerimine', language: 'Keel', difficulty: 'Raskusaste', sound: 'Heli', easy: 'Lihtne', normal: 'Tavaline', hard: 'Raske', score: 'Punktid', combo: 'Kombinatsioon', time: 'Aeg', threshold: 'Lävi: {value}', smaller: 'Väiksem kui {value}', atLeast: '{value} või suurem', correct: 'Õige!', incorrect: 'Mitte päris — proovi järgmist.', accuracy: 'Täpsus: {value}%', reset: 'Lähtesta statistika', highScore: 'Kõrgeim tulemus', longestStreak: 'Pikim seeria', settings: 'Ava seaded', controls: 'Kasuta vasakut/paremat noolt või A/D.' },
    ja: { appName: 'クイックソート', language: '言語', difficulty: '難易度', sound: 'サウンド', easy: '簡単', normal: '普通', hard: '難しい', score: 'スコア', combo: 'コンボ', time: '時間', threshold: 'しきい値: {value}', smaller: '{value} 未満', atLeast: '{value} 以上', correct: '正解！', incorrect: '惜しい！次を試してみよう。', accuracy: '正確さ: {value}%', reset: '統計をリセット', highScore: '最高スコア', longestStreak: '最長連続記録', settings: '設定を開く', controls: '左右の矢印キーまたは A/D を使って選択。' },
    ko: { appName: '빠른 분류', language: '언어', difficulty: '난이도', sound: '소리', easy: '쉬움', normal: '보통', hard: '어려움', score: '점수', combo: '콤보', time: '시간', threshold: '기준값: {value}', smaller: '{value}보다 작음', atLeast: '{value} 이상', correct: '정답!', incorrect: '조금 아쉬워요 — 다음을 시도하세요.', accuracy: '정확도: {value}%', reset: '통계 초기화', highScore: '최고 점수', longestStreak: '최장 연속 기록', settings: '설정 열기', controls: '왼쪽/오른쪽 화살표 또는 A/D를 사용하세요.' },
    zh: { appName: '快速分类', language: '语言', difficulty: '难度', sound: '声音', easy: '简单', normal: '普通', hard: '困难', score: '得分', combo: '连击', time: '时间', threshold: '阈值: {value}', smaller: '小于 {value}', atLeast: '{value} 或更大', correct: '正确！', incorrect: '还不对，试试下一个。', accuracy: '准确率: {value}%', reset: '重置统计数据', highScore: '最高得分', longestStreak: '最长连胜', settings: '打开设置', controls: '使用左右方向键或 A/D 选择。' },
    it: { appName: 'Ordinamento rapido', language: 'Lingua', difficulty: 'Difficoltà', sound: 'Suono', easy: 'Facile', normal: 'Normale', hard: 'Difficile', score: 'Punteggio', combo: 'Combo', time: 'Tempo', threshold: 'Soglia: {value}', smaller: 'Minore di {value}', atLeast: '{value} o maggiore', correct: 'Corretto!', incorrect: 'Non proprio — prova il prossimo.', accuracy: 'Precisione: {value}%', reset: 'Reimposta statistiche', highScore: 'Punteggio più alto', longestStreak: 'Serie più lunga', settings: 'Apri impostazioni', controls: 'Usa le frecce sinistra/destra o A/D per scegliere.' }
};
const footerLabels = { en: { donate: "Donate", version: "Version 1.0.0" }, fa: { donate: "حمایت مالی", version: "نسخه ۱.۰.۰" }, ar: { donate: "تبرّع", version: "الإصدار ١.٠.٠" }, es: { donate: "Donar", version: "Versión 1.0.0" }, fr: { donate: "Faire un don", version: "Version 1.0.0" }, de: { donate: "Spenden", version: "Version 1.0.0" }, tr: { donate: "Bağış yap", version: "Sürüm 1.0.0" }, sv: { donate: "Donera", version: "Version 1.0.0" }, et: { donate: "Anneta", version: "Versioon 1.0.0" }, ja: { donate: "寄付", version: "バージョン 1.0.0" }, ko: { donate: "후원", version: "버전 1.0.0" }, zh: { donate: "捐赠", version: "版本 1.0.0" }, it: { donate: "Dona", version: "Versione 1.0.0" } };
export const localeMeta = { en: { name: 'English', rtl: false, intl: 'en-US' }, fa: { name: 'فارسی', rtl: true, intl: 'fa-IR' }, ar: { name: 'العربية', rtl: true, intl: 'ar' }, es: { name: 'Español', rtl: false, intl: 'es-ES' }, fr: { name: 'Français', rtl: false, intl: 'fr-FR' }, de: { name: 'Deutsch', rtl: false, intl: 'de-DE' }, tr: { name: 'Türkçe', rtl: false, intl: 'tr-TR' }, sv: { name: 'Svenska', rtl: false, intl: 'sv-SE' }, et: { name: 'Eesti', rtl: false, intl: 'et-EE' }, ja: { name: '日本語', rtl: false, intl: 'ja-JP' }, ko: { name: '한국어', rtl: false, intl: 'ko-KR' }, zh: { name: '中文', rtl: false, intl: 'zh-CN' }, it: { name: 'Italiano', rtl: false, intl: 'it-IT' } };
export function translator(locale) { const m = { ...en, ...(locale === 'en' ? {} : packs[locale]) }; return (key, params = {}) => (footerLabels[locale]?.[key] ?? m[key] ?? key).replace(/\{(\w+)\}/g, (_match, key) => String(params[key] ?? '')); }
